apiVersion: v1
kind: Pod
metadata:
  name: pod6
spec:
  containers:
  - image: busybox:1.31.0
    name: pod6-container
    resources: {}
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/ready
      initialDelaySeconds: 5
      periodSeconds: 10
    command:
    - sh
    - -c
    - touch /tmp/ready && sleep 1d
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}